spring.application.name=tardiness-report
spring.datasource.url=jdbc:postgresql://160.16.197.189:5432/postgres?currentSchema=tardinessreport
spring.datasource.username=postgres
spring.datasource.password=lg82o7o9
spring.datasource.driver-class-name=org.postgresql.Driver